# capacity and true_resolution should match for embedder and extractor
# this is redundant, but more convenient for parsing.

embedder:
  capacity: 32
  num_layers: 3
  true_resolution: 256
  # Embedder is much shallower compared to extractor, try turning off StochasticPath for embedder
  cnext_drop: 0

extractor:
  # Equivalent to ConvNeXt-T (T = Tiny)
  capacity: 32
  true_resolution: 256
  channel_muls: [1, 2, 4, 8]
  blocks: [3, 3, 9, 3]
  cnext_drop: 0.1

augmentations:
  train:
    DiffJPEG:
      min_quality: 40
      max_quality: 80
    
    GaussianBlur:
      min_kernel_size: 3
      max_kernel_size: 17
    
    Brightness:
      min_factor: 0.5
      max_factor: 2
    
    Contrast:
      min_factor: 0.5
      max_factor: 2
    
    Saturation:
      min_factor: 0.5
      max_factor: 2
    
    Hue:
      min_factor: -0.1
      max_factor: 0.1
    
    Rotate:
      min_angle: -10
      max_angle: 10
    
    Resize:
      min_size: 0.5
      max_size: 1.5
    
    Crop:
      min_size: 0.33
      max_size: 1
    
    Perspective:
      min_distortion_scale: 0.1
      max_distortion_scale: 0.5
    
    HorizontalFlip:
      # No parameters

    Identity:
      # No parameters

    Combine:
      min_quality: 40
      max_quality: 80
      min_brightness_factor: 0.5
      max_brightness_factor: 2
      min_distortion_scale: 0.1
      max_distortion_scale: 0.5
    
    PixelSplicing:
      min_p: 0.05
      max_p: 0.35
    
    BoxSplicing:
      min_size: 0.1
      max_size: 0.7